### ISSUE TITLE
Question about adding movie list

### ISSUE THREAD

**Issue by Lindefor** [iprog-vt2023-grp23/StreaMore#80]
MyListPagePresenter:
const addMovieList = (listName) => {
    if(listName === ""){
      return;
    }
    dispatch(addNewMovieList(listName));
  }

SearchListPresenter:
const onAddNewMovieList = (listName) => {
    dispatch(addNewMovieList( listName ));
  };

Should be same with listName==="" ?

**Comment by GabbeLandin** [comment]
jaa, det tror jag
